#!/bin/bash
# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Display menu
echo -e " ${YELLOW}🏛🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛🏛${NC}"

echo "       pxyUpdate           u-Update pxy"
echo "       Run                 r-Run PXY"
echo "       Env                 e-Get on Env"
echo "       Buy                 n-Night Buy"
echo "       Kill-all            a-SquireOff-ALL
echo "       Kill-buy            b-SquireOff-buy
echo "       Kill-sell           s-SquireOff-sell
echo "       Profit              p-Show me prifit"
echo "       Profit-Table        t-Show prifit Table"
echo "       Exit                0-Or Simply exit"

echo -e " ${YELLOW}🏛🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛🏛${NC}"
# Get user input
read -t 10 -p "Enter your choice: " choice

# Perform actions based on user input
case $choice in
    n)
        echo "Executing pxybuy - Night Buy"
        pxybuy
        ;;
    e)
        echo "Executing pxyenv - Get on Environment"
        pxyenv
        ;;
    a)
        echo "Executing pxykill - SquireOff all Positions"
        pxykill
        ;;
    b)
        echo "Executing pxykillbuy - Sell all Buy Positions"
        pxykillbuy
        ;;
    s)
        echo "Executing pxykillsell - Rename sys/exe/pxykillsell to sys/pxykillsell"
        pxykillsell
        ;;
    u)
        echo "Executing pxyupdate - Update pxyupdate"
        pxyupdate
        ;;
    r)
        echo "Waiting for 5 seconds..."
        sleep 5
        echo "Running 'pxy'"
        pxyrun
        ;;
    0)
        echo "Exiting the script. Goodbye!"
        exit 0
        ;;

    p)
        echo "Profit"
        pxytprft
        ;;

    t)
        echo "Profit Table"
        pxytblprft
        ;;


    "")
        # Empty input (user didn't make a choice in 5 seconds)
        echo "No input received in the last 5 seconds. Running 'pxy'"
        pxyrun
        ;;
    *)
        # Invalid choice
        echo "Invalid choice. Please enter a number between 1 and 8."
        ;;
esac





