#!/bin/bash
# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Display menu
echo -e " ${YELLOW}🏛🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛🏛${NC}"

echo "     nb              -Night Buy"
echo "     e               -Get on Env"
echo "     ka              -SquireOff-ALL"
echo "     kb              -Sell all Buy"
echo "     ks              -Buy all Sell"
echo "     u               -Update pxy"
echo "     m               -Run PXY"
echo "     c               -Control pxy"
echo "     p               -Show me prifit"
echo "     pl              -Show prifit Table"
echo "     r               -Or Simply exit"

echo -e " ${YELLOW}🏛🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛🏛${NC}"
# Get user input
read -t 10 -p "Enter your choice: " choice

# Perform actions based on user input
case $choice in
    nb)
        echo "Executing pxybuy - Night Buy"
        pxybuy
        ;;
    e)
        echo "Executing pxyenv - Get on Environment"
        pxyenv
        ;;
    ka)
        echo "Executing pxykill - SquireOff all Positions"
        pxykill
        ;;
    kb)
        echo "Executing pxykillbuy - Sell all Buy Positions"
        pxykillbuy
        ;;
    ks)
        echo "Executing pxykillsell - Rename sys/exe/pxykillsell to sys/pxykillsell"
        pxykillsell
        ;;
    u)
        echo "Executing pxyupdate - Update pxyupdate"
        pxyupdate
        ;;
    m)
        echo "Waiting for 5 seconds..."
        sleep 5
        echo "Running 'pxy'"
        pxyrun
        ;;
    c)
        echo "Profit Table"
        pxycntrl
        ;;
    p)
        echo "Profit"
        pxytprft
        ;;

    pl)
        echo "Profit Table"
        pxytblprft
        ;;

    r)
        # Empty input (user didn't make a choice in 5 seconds)
        echo "No input received in the last 5 seconds. Running 'pxy'"
        pxyrun
        ;;
    *)
        echo "Exiting the script. Goodbye!"
        exit 0
        ;;
esac

