#!/bin/bash

source ~/env/bin/activate

# Change to the script's directory
cd ~/pxy/sys/exe/run

# Prompt the user for input
echo "Enter the name of the Python script to run:"
read script_name

# Run the Python script with the user-provided input
python3 "$script_name"pxy.py
