#!/bin/bash
cd /home/userland/pxy
git pull

sudo cp ~/pxy/sys/*xy /usr/local/bin/

sudo chmod +x /usr/local/bin/*xy# Activate the virtual environment

source ~/env/bin/activate

# Change to the script's directory
cd ~/pxy/sys/exe/run

# Run the Python script
python3 pxy.py
