#!/bin/bash
cd /home/userland/pxy
git pull
# Activate the virtual environment
source ~/env/bin/activate

# Change to the script's directory
cd ~/pxy/sys/exe/run

# Run the Python script
python3 cntrlpxy.py
